import uuid
from datetime import datetime, timezone
from typing import List, Dict, Any, Optional

from pydantic import BaseModel, Field

class DecisionRecord(BaseModel):
    """
    Schema for an auditable AI decision record.
    Ensures that every decision logged meets the required structure for auditability.
    """
    decision_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    timestamp: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    
    model: str = Field(..., description="The model used for the decision, e.g., 'llama3.2:1b'")
    config: Dict[str, Any] = Field(..., description="Configuration for the model, e.g., {'temperature': 0.7}")
    
    prompt: str = Field(..., description="The exact prompt that triggered the decision.")
    context_sources: List[str] = Field(..., description="A list of sources used as context for the decision.")
    
    output: str = Field(..., description="The output generated by the model.")
    
    confidence: Optional[float] = Field(None, description="A score representing the model's confidence in its output.")
    risk_flags: List[str] = Field(default_factory=list, description="Flags for potential risks, e.g., ['hallucination_risk']")
    
    prev_hash: str = Field(..., description="The hash of the previous decision record, ensuring chronological integrity.")
    hash: str = Field(..., description="The hash of this decision record, providing tamper-evidence.")

    class Config:
        # Pydantic models are immutable by default, which is good for this use case.
        frozen = True
